travis:
  secure:
    BINSTAR_TOKEN: FqxX3fVBY1yozHwILe3zi/NyjWeuYshgSg+c6G6rHn7O/tkZ5n1eoDDw5c8H8/UptGOI4ZGb/jgK1pthetAXDSdUfIfy+sOoPO7IJSCkMkamffwf+g38wTHLYhWMXkRlw4Fujw6KS7C+2s1jb/7cPV1yQeuWtD7KKQR2acuJYEQD4t5GdncvrPQBGcEnv1gdZtGZICVstQ7bVNLx6JZomqGnaujlYrtZSO/OMJHhz1jEvvrVKkxNAD+cUSr0FJzkRs8uyF3/WiJ6HpSUoB+yFRnYWEx1tguK1rW0L49RxPnOod8nkOjaZaSya9yFG+3SWR/6wVWNoBgvUzz4jaC+9LHUJ483FQJnRIiAde+q1Oy6qByZs6IvRQeMevZc3pqb3Dl5IhNdnSbrFuwdj8MoY3WNjKSrpXFXMMwsJJfZVvhSjXKQx/NMZqsdFsimRgrcAMCDgo+5SurJk+CJF5XjbT36bsWUu9DUZ13Qq8WZqm2bhx1k6LFBhNOXB3QF9kd+8vPeb2CsB/gKWrUchxKJQ3BwLXw+ECAYKb7D9Pag3g7QSvBL0D683dSM0qvfjpzfpQt9izbsnRmSrigwh5TxY/QHVUeYhFiQSoeNeRj//eNCVmKUAvnPsuSYhPIn/rtv/y3tJ0/ZcYVwhiIQ2j2y7SJ8+QmC1RD7SdDD+P4WmeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
